automate.h
uint16_t CurrentTime
uint16_t TimeStop
uint16_t TimeSupply
uint16_t adc6
uint16_t adc7
void StateAutomate()
References flags, PackedBool::State_Automate, KeyCurrentCode, AddTask, Supply_sw, Fire_sw, Timer_sw, Furnance_sw, IND_OutputFormatChar, StateAutomate.
Referenced by StateAutomate, main.
void ShowAdc6()
References AddTask, FuncINDTime, IND_Time, adc6.
Referenced by AdcMean.
void ShowAdc7()
References AddTask, FuncINDTime, IND_Time, adc7.
Referenced by AdcMean.
void AddTask(void(*taskfunc)(void), uint16_t taskdelay)
References TaskArray, MAXnTASKS, task::countdown, task::pfunc, delay_time, dt.
void FuncINDTime()
References IND_Time, TimeSupply, TimeStop, AddTask, FuncINDTime.
Referenced by Timer_sw, Supply_sw, FuncINDTime, Furnance_sw, Fire_sw, ShowAdc6, ShowAdc7, main.
void FuncINDOutput()
void Furnance_sw()
References AddTask, FuncINDTime, IND_OutputFormatChar, CH, CB, SB, KeyCurrentCode.
Referenced by StateAutomate.
void Fire_sw()
References AddTask, FuncINDTime, IND_OutputFormatChar, CH, CB, SB, KeyCurrentCode.
Referenced by StateAutomate.
void Supply_sw()
References AddTask, FuncINDTime, IND_OutputFormatChar, flags, PackedBool::SupplyAuto, TimeSupply, adc7, TimeStop, adc6, CurrentTime, CH, CB, SB.
Referenced by StateAutomate.
void Timer_sw()
References AddTask, FuncINDTime, flags, PackedBool::SupplyAuto, IND_OutputFormatChar, PackedBool::ADC_Channel, CurrentTime, adc7, TimeStop, adc6, TimeSupply, SB, CB, KeyCurrentCode.
Referenced by StateAutomate.