dispatch.c
void AddTask(void(*taskfunc)(void), uint16_t taskdelay)
References TaskArray, MAXnTASKS, task::countdown, task::pfunc, delay_time, dt.
Referenced by ISR, AdcMean, StateAutomate, Timer_sw, Supply_sw, FuncINDTime, Furnance_sw, Fire_sw, ShowAdc6, ShowAdc7, IND_Update, KeyScan, main, doubleCountdown.
void DispatchTask(void)
Прототипы фукнций ////////.
References flags, PackedBool::RunFlag, TaskArray, task::pfunc, MAXnTASKS, task::countdown, dt, delay_time.
Referenced by main.
void DeleteTask(uint8_t j)
References TaskArray, task::pfunc, task::countdown.
ISR(TIMER2_OVF_vect)
References StartFrom, flags, PackedBool::RunFlag, delay_time.
void InitScheduler(void)
References StartFrom.
Referenced by main.