indicator.h
IND_AMOUNT_NUM
Referenced by IND_OutputFormatChar, IND_Init, IND_Output, IND_OutputFormat, IND_Update.
IND_SCAN_SEGMENT
IND_ACTIVE_LEVEL_SEG
IND_ACTIVE_LEVEL_DIG
IND_PORT_SEG
Referenced by IND_Init, IND_Update.
IND_DDR_SEG
Referenced by IND_Init.
IND_PORT_DIG
Referenced by IND_Init, IND_Update.
IND_DDR_DIG
Referenced by IND_Init.
IND_SHIFT_REG_SEG
Referenced by IND_Update.
IND_SHIFT_REG_DIG1
Referenced by IND_Update.
IND_SHIFT_REG_DIG2
Referenced by IND_Update.
IND_NUM1
IND_NUM2
IND_NUM3
IND_NUM4
IND_NUM5
IND_NUM6
IND_NUM7
IND_NUM8
IND_NUM9
IND_NUM10
IND_NUM11
IND_NUM12
IND_NUM13
IND_NUM14
IND_NUM15
IND_NUM16
IND_A
Referenced by IND_Init.
IND_B
Referenced by IND_Init.
IND_C
Referenced by IND_Init.
IND_D
Referenced by IND_Init.
IND_E
Referenced by IND_Init.
IND_F
Referenced by IND_Init.
IND_G
Referenced by IND_Init.
IND_COM
Referenced by IND_OutputFormatChar, IND_Time, IND_Init, IND_Output, IND_OutputFormat.
void IND_Init(void)
References i, IND_PORT_SEG, IND_A, IND_B, IND_C, IND_D, IND_E, IND_F, IND_G, IND_COM, IND_DDR_SEG, IND_AMOUNT_NUM, IND_PORT_DIG, IND_DDR_DIG, SPI_Init, ind_buf.
Referenced by main.
void IND_Output(uint16_t value, uint8_t comma)
References i, IND_AMOUNT_NUM, ind_buf, number, IND_EMPTY_NUM, IND_COM.
void IND_OutputFormat(uint16_t value, uint8_t comma, uint8_t position, uint8_t amount)
References i, IND_AMOUNT_NUM, ind_buf, number, IND_EMPTY_NUM, IND_COM.
void IND_Update(void)
References i, IND_LightOutSeg, IND_SHIFT_REG_SEG, IND_LIGHT_OUT, IND_AMOUNT_NUM, IND_LightOutDig, IND_SHIFT_REG_DIG1, IND_SHIFT_REG_DIG2, SPI_WriteArray, ind_buf, IND_OutDig, IND_OutSeg, IND_PORT_SEG, IND_PORT_DIG, AddTask, IND_Update.
Referenced by IND_Update, main.
void IND_OutputFormatChar(char char_string[], uint8_t comma, uint8_t position)
References i, number, ind_buf, IND_AMOUNT_NUM, IND_COM.
Referenced by StateAutomate, Timer_sw, Supply_sw, Furnance_sw, Fire_sw.
uint8_t ascii2int(uint8_t symbol)
void IND_RunString(char ch_string, uint8_t speed, uint8_t field, uint8_t amount, uint8_t comma)
void IND_Time(uint16_t CurrentTime, uint8_t position)
вывод на индикатор минут и секунд. вход кол-во секунд с ацп argument2 explanation . . . обновление буффера индикатора
References ind_buf, number, IND_COM.
Referenced by FuncINDTime, ShowAdc6, ShowAdc7.
void AddTask(void(*taskfunc)(void), uint16_t taskdelay)