kbd.c
void InitControl()
Referenced by main.
uint8_t KeyCode()
References flags, PackedBool::KeyPin.
void KeyState()
References flags, PackedBool::KeyPressed, PackedBool::KeyReleased, PackedBool::KeyPushLong, PackedBool::KeyPin, PackedBool::State_Automate, KeyCurrentCode.
Referenced by KeyScan.
void KeyScan()
References flags, PackedBool::KeyReleased, i, PackedBool::KeyPressed, PackedBool::KeyPin, PackedBool::KeyPushLong, KeyState, AddTask, KeyScan.
Referenced by KeyScan, main.