timer.h
uint16_t TimeStop
Referenced by Timer_sw, Supply_sw, FuncINDTime, doubleCountdown.
uint16_t TimeSupply
Referenced by Timer_sw, Supply_sw, FuncINDTime, doubleCountdown.
uint16_t CurrentTime
Referenced by Timer_sw, Supply_sw, doubleCountdown.
uint16_t adc6
Referenced by AdcMean, Timer_sw, Supply_sw, ShowAdc6, doubleCountdown.
uint16_t adc7
Referenced by AdcMean, Timer_sw, Supply_sw, ShowAdc7, doubleCountdown.
void InitTimer()
References TCNT0_const.
Referenced by main.
void doubleCountdown()
Referenced by main, doubleCountdown.
void KeyState()
Referenced by KeyScan.
void KeyScan()
Referenced by KeyScan, main.
void IND_Update()
void IND_Time(uint16_t CurrentTime, uint8_t position)
void AddTask(void(*taskfunc)(void), uint16_t taskdelay)
Referenced by ISR, AdcMean, StateAutomate, Timer_sw, Supply_sw, FuncINDTime, Furnance_sw, Fire_sw, ShowAdc6, ShowAdc7, IND_Update, KeyScan, main, doubleCountdown.