timer.c
ISR(TIMER1_OVF_vect)
References flags, PackedBool::SupplyAuto, PackedBool::TimerFlag.
void doubleCountdown()
References flags, PackedBool::TimerFlag, PackedBool::SupplyAuto, CurrentTime, PackedBool::ADC_Channel, adc6, TimeSupply, SB, adc7, TimeStop, CB, AddTask, doubleCountdown.
Referenced by main, doubleCountdown.
void InitTimer()
References TCNT0_const.
Referenced by main.
ISR(TIMER0_OVF_vect)
References TCNT0_const.